# Generated by Django 5.2.7 on 2025-10-06 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={},
        ),
        migrations.AlterModelOptions(
            name="show",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_booked_seat_per_show",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="bookings_bo_show_id_0cfb91_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="bookings_bo_user_id_5943d6_idx",
        ),
        migrations.RemoveIndex(
            model_name="show",
            name="bookings_sh_date_ti_0ce4a5_idx",
        ),
        migrations.RemoveIndex(
            model_name="show",
            name="bookings_sh_movie_i_94545c_idx",
        ),
        migrations.AlterField(
            model_name="booking",
            name="seat_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("booked", "Booked"), ("cancelled", "Cancelled")],
                default="booked",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "booked")),
                fields=("show", "seat_number"),
                name="unique_booked_seat",
            ),
        ),
    ]
